### ISSUE TITLE
Fix JWT example in security document

### ISSUE THREAD

**Issue by benjie** [graphile/graphile.github.io#17]
See: https://github.com/graphile/graphile-build/issues/69

**Comment by benjie** [comment]
Both approaches are valid; are you facing an issue with one of them? It honestly shouldn’t matter if it’s public or private- it’s just a type so it doesn’t store data.

**Comment by AdrienPensart** [comment]
Ok I finally understood, I missed this line in example : "a composite type cannot store rows"
So it is perfectly valid to let jwt_token in public schema !

Thank you for this tip.

But I think https://www.graphile.org/postgraphile/security/#generating-jwts is still misleading, as it assumes "account my_public_schema.person_account" to contain "account.password_hash", something that "should" be forbidden in the public schema, as claimed by the other link : 

`Why would we choose to create a new table in the forum_example_private schema instead of just adding columns to  forum_example.person? There are a couple of answers to this question. The first and most fundamental is seperation of concerns. By moving  email and password_hash to a second table we make it much harder to accidently select those values when reading forum_example.person. Also, users will not have the permission to directly query data from forum_example_private (as we will see) making this approach more secure. This approach is also good for PostGraphile as the forum_example_private schema is never exposed in PostGraphile, so you will never accidently expose password hashes in GraphQL.`

in https://www.graphile.org/postgraphile/postgresql-schema-design/#storing-emails-and-passwords

**Comment by benjie** [comment]
You're right; that's terrible - bcrypt password should NOT be in public schema. That whole guide needs rewriting really to adopt the conventions of `app_public` / `app_private` / etc for consistency.

**Comment by AdrienPensart** [comment]
Sorry to bother, but there is another quirk:

https://www.graphile.org/postgraphile/security/#how-it-works

`create function current_user_id() returns integer as $$
  select nullif(current_setting('jwt.claims.user_id', true), '')::integer;
$$ language sql stable security definer;`

https://www.graphile.org/postgraphile/postgresql-schema-design/#using-the-authorized-user

`create function forum_example.current_person() returns forum_example.person as $$
  select *
  from forum_example.person
  where id = current_setting('jwt.claims.person_id')::integer
$$ language sql stable;`

Why do we need "security definer" in the first case, and not in the second ?

**Comment by benjie** [comment]
It's not necessary, but does no harm. Better to omit it 👍
