### ISSUE TITLE
What do you think about add "Postgraphile vs Prisma" in « FAQ section » ?

### ISSUE THREAD

**Issue by stephane-klein** [graphile/graphile.github.io#202]
Hi,

what do you think about add "Postgraphile vs [Prisma](https://github.com/prisma)" in « FAQ section » ?

I think something like : https://www.terraform.io/intro/vs/index.html

Best regards,
Stéphane

**Comment by hos** [comment]
I was also interested `Postgraphile vs Hasura` few days ago. And actually first it was hard to find
someone explaining key points. I think definitely it is important question, thought can't provide answers as I have no experience in hasura.

**Comment by jemgillam** [comment]
I'm going to close this because I don't think it is appropriate to include comparisons with other products on our website.  If there is a particular feature list of PostGraphile you'd like to see on the website, that might work better. 

Remaining unbiased and keeping comparisons fair and up to date is a significant undertaking, which would distract from more important tasks. 

We believe this is a better fit for community-written articles or blog posts, and should anyone wish to write one we would be happy to fact check the PostGraphile portions of it.
